### PR TITLE
Master

### PR DESCRIPTION
**Pull request by duxbuse**
Hopefull this can be auto merged

### CODE REVIEW

**Comment by duxbuse** [comment]
@Karanadon I dont want to hit go unless it might break something. Can you check it out.

**Comment by Karanadon** [comment]
Any idea why it comes up with all the other commits from earlier?

**Comment by duxbuse** [comment]
I think because I couldn't edit the VC file as my local copy was behind the master branch. When I merged the BSData branch into mine I got all those commits then I made a commit then did the pull request so my pull includes all changes to my local file which included the merge commits?

I dont know git hub is this mysterious black box that gives me the shits :P

**Comment by Karanadon** [comment]
I've made a backup just in case so will just merge.

**Pull request merged**
