### PR TITLE
SE Clean up categories

### PR DESCRIPTION
**Pull request by nick-lironi-irvine**
Remove Fleet of Foot references, and add names to category links to make them easier to read

### CODE REVIEW

**Comment by Karanadon** [comment]
What are you using to edit files? I have no issues seeing the correct categories?

**Comment by nick-lironi-irvine** [comment]
Edit files? A plain text editor! Which is also why I can see the redundant/incorrect Fleet of Foot category links, even if they weren't visible in the Battlescribe Data Editor UI. They were certainly still being applied, incorrectly causing my list to appear invalid

**Comment by Karanadon** [comment]
Why not just use the data editor? I have removed the Fleet of Foot and Forest Giant redundant categories which should remove all links to them. You could have also been getting an invalid list from the weird change to category contribution, which I have now fixed as well (hopefully).

**Comment by nick-lironi-irvine** [comment]
I use the data editor sometimes, but it's got horrifically klunky UX and it almost pains me to use it.... find+replace in text editor is much faster/more efficient for certain tasks. In any case, sounds like you've solved the main issue another way, feel free to decline the PR

**Comment by Karanadon** [comment]
Hopefully in the future we will have an automatic tool which looks up values in the books and searches and replaces the values in the text file for Battlescribe! So will be a lot less manual data entry.

**Pull request merged**
