### PR TITLE
Master

### PR DESCRIPTION
**Pull request by duxbuse**
Updated VC to v1.0

### CODE REVIEW

**Comment by Arturius1** [comment]
@duxbuse - This branch has conflicts that must be resolved.

I think it's because of 3 commits in 1.

Please do a new commit with just one change - VC to 1.0, then I will try to merge it.

**Comment by duxbuse** [comment]
ok give it a try now.

**Comment by duxbuse** [comment]
It says that there are still conflicts, but it wont show them to me so im not sure what to change?

**Comment by Arturius1** [comment]
no idea :/

@duxbuse please send file manually to my email, will upload it the hard way

**Pull request closed without merging**
