### PR TITLE
Fix #588 - Mage wizard adept mount options in queens cavalier

### LINKED ISSUE #588: HE: Wizard adepts cannot take any mount

### PR DESCRIPTION
**Pull request by rzmoz**

### CODE REVIEW

**Comment by rzmoz** [comment]
@DarkSkyT9A mistake. Trying to correct it AWS

**Comment by rzmoz** [comment]
A Temple Lamassu is a wizard apprentice by default but it can be upgraded to an Adept (It's a wizard on its own independant from the character)

**Comment by rzmoz** [comment]
The commit should've been in the other issue #592

**Comment by rzmoz** [comment]
@DarkSkyT9A latest changes to ID removed the option of upgrading the TL to a wizard adept so the current file is broken and a valid selection not possible (p8. in ID)

**Comment by rzmoz** [comment]
ID commit has been removed from this PR. Please disregard the ID changes here.

**Comment by DarkSkyT9A** [comment]
Okay. But while we are at it: you should implement it as an upgrade to the Lamassu not as a separate mount option. Some other mounts have upgrades or options as well.

**Comment by rzmoz** [comment]
@DarkSkyT9A the reason it was flattened (instead of mount option) was because it then takes about 6 clicks instead 1 to add an adept and it doesn't show up in any overviews anywhere => really poor usability. I would suggest to review those other mounts instead (I don't have a clear overview of them)

**Comment by rzmoz** [comment]
Latest Fix is a but more complex than needed because the append name with xxx didn't work for some reason

**Pull request closed without merging**
