### PR TITLE
Vermin swarm update to v1.2.1 and battlescribe 2.0!

### PR DESCRIPTION
**Pull request by beckian**
vermin categories added to gst file
common rules transfered to gst but not checked against v1.2 yet
vermin special rules updated to v1.2.1

### CODE REVIEW

**Comment by duxbuse** [comment]
You will need to resolve the game system conflicts before we can merge your commits

**Comment by Karanadon** [comment]
What's with the BH file changes?

**Comment by Karanadon** [comment]
I think it's fine to leave all the individual rules in catalogs for now... Can you detail what changes were made to the game system file for 2.0?

**Comment by beckian** [comment]
Don't merge any of my rubbish yet, I think I have got myself confused here. The outcome of trying to do something new whilst ill and tired. I thought I had only opened the BH to have a look and compare.

**Pull request closed without merging**
