### PR TITLE
Master

### PR DESCRIPTION
**Pull request by duxbuse**
Updated VC to 99.4.1

### CODE REVIEW

**Comment by Arturius1** [comment]
@bombastian2000 please look into this Ogre Khans update - to check if it's compatible with your recent work on that file

**Comment by duxbuse** [comment]
@bombastian2000 these were updates to the OK file for 99.1. So if its 100% for 99.4 then these changes can be disregarded.

**Comment by Arturius1** [comment]
@duxbuse please do a new pull request for VC only
as I am not sure OK is ok :) I want to merge VC and cannot do this now with this pull (OK and VC in one)

**Comment by duxbuse** [comment]
@Arturius1 Any idea how to get the pull request to ignore a commit. I cant seem to get rid of the OK commits

**Comment by Arturius1** [comment]
@duxbuse sorry, no idea how to fish out just this one file from a multi-file commit

please do separate commit with VC file only

**Pull request closed without merging**
